version: '3'

networks:
    yolov8-net:
        driver: bridge

services:
    yolov8:
        image: viphap/yolov8-server:latest
        ports:
            - 5000:5000
        environment:
            - YOLO_MODEL=yolov8l.onnx
        networks:
            - yolov8-net
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
