version: '3'

networks:
    yolov8-net:
        driver: bridge

services:
    yolov8:
        images: yolov8-server:latest
        ports:
            - 5000:5000
        networks:
            - yolov8-net
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
