version: '3'

networks:
    yolo-net:
        driver: bridge

services:
    yolo:
        image: viphap/yolo-server:latest
        ports:
            - 5000:5000
        networks:
            - yolo-net
        volumes:
            - ./models:/home/app/app/yolo/models
        environment:
            - MODEL=yolov8l
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        restart: always
