version: '3'

networks:
    yolo-net:
        driver: bridge

services:
    yolo:
        image: viphap/yolo-server:latest
        environment:
            - MODEL=yolov8l
        ports:
            - 5000:5000
        networks:
            - yolo-net
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        command: /bin/sh -c "init.sh"
        restart: always
